import {CodexPreview} from './codex-preview.mjs';
const $=id=>document.getElementById(id);let item=null,config=null,preview=new CodexPreview($('desktopPreview')),dragKey=null,textDrag=null,dark=false;
const defaults=(w,h)=>({width:w,height:h,left:Math.round(w*.35),right:Math.round(w*.73),top:Math.round(h*.45),bottom:Math.round(h*.55),scale:Math.max(.01,Math.min(.6,240/w,98/h)),padding:[29,37,36,48],color:'#44362f',radius:0,borderWidth:0,borderColor:'#d0d0d0'});
function toast(s){$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3000)}
function setInputs(){for(const k of ['radius','borderWidth','borderColor','color'])$(k).value=config[k];$('scale').value=(config.scale*100).toFixed(2);}
function textRect(){const s=config.scale;return{left:config.padding[3]/s,top:config.padding[0]/s,right:item.width-config.padding[1]/s,bottom:item.height-config.padding[2]/s};}
function update(){if(!item)return;const wrap=$('.art-wrap'),size=Math.min(1.7,(wrap.clientWidth-60)/item.width,430/item.height),art=$('art');art.style.width=item.width*size+'px';art.style.height=item.height*size+'px';const sx=art.clientWidth/item.width,sy=art.clientHeight/item.height;for(const k of ['left','right','top','bottom']){const el=document.querySelector(`[data-key="${k}"]`);el.style[k==='left'||k==='right'?'left':'top']=config[k]*(k==='left'||k==='right'?sx:sy)+'px';}$('stretchBand').style.cssText=`left:${config.left*sx}px;top:${config.top*sy}px;width:${(config.right-config.left)*sx}px;height:${(config.bottom-config.top)*sy}px`;const b=textRect();$('textBox').style.cssText=`left:${b.left*sx}px;top:${b.top*sy}px;width:${Math.max(8,b.right-b.left)*sx}px;height:${Math.max(8,b.bottom-b.top)*sy}px`;preview.setAsset(item.url,config);}
function read(){config.scale=Number($('scale').value)/100;config.radius=Number($('radius').value);config.borderWidth=Number($('borderWidth').value);config.color=$('color').value;config.borderColor=$('borderColor').value;update();}
function openItem(name,data,initial){const blob=new Blob([Uint8Array.from(atob(data),c=>c.charCodeAt(0))],{type:'image/png'});item={name,filename:name,width:0,height:0,url:URL.createObjectURL(blob)};const image=new Image();image.onload=()=>{item.width=image.naturalWidth;item.height=image.naturalHeight;config={...defaults(item.width,item.height),...(initial||{})};$('image').src=item.url;$('filename').textContent=name;setInputs();update();};image.src=item.url;}
function fileOpen(file){const reader=new FileReader();reader.onload=()=>openItem(file.name,String(reader.result).split(',')[1]);reader.readAsDataURL(file);}
$('file').onchange=e=>{if(e.target.files[0])fileOpen(e.target.files[0]);};
for(const k of ['scale','radius','borderWidth','borderColor','color'])$(k).oninput=read;
$('fit').onclick=()=>{if(item){config.scale=defaults(item.width,item.height).scale;setInputs();update();}};$('reset').onclick=()=>{if(item){config={...defaults(item.width,item.height),padding:[29,37,36,48]};setInputs();update();}};$('theme').onclick=()=>{dark=!dark;preview.dark=dark;$('theme').textContent=dark?'浅色预览 ☼':'深色预览 ☾';preview.build();update();};$('back').onclick=()=>location.href='gallery.html';
for(const line of document.querySelectorAll('.guide')){line.onpointerdown=e=>{dragKey=line.dataset.key;line.setPointerCapture(e.pointerId)};line.onpointermove=e=>{if(!dragKey||!line.hasPointerCapture(e.pointerId))return;const r=$('art').getBoundingClientRect(),axis=dragKey==='left'||dragKey==='right',v=Math.round((axis?e.clientX-r.left:e.clientY-r.top)/(axis?r.width/item.width:r.height/item.height)),bounds={left:[1,config.right-1],right:[config.left+1,item.width-1],top:[1,config.bottom-1],bottom:[config.top+1,item.height-1]};config[dragKey]=Math.max(bounds[dragKey][0],Math.min(bounds[dragKey][1],v));update()};line.onpointerup=()=>{dragKey=null;};}
$('textBox').onpointerdown=e=>{textDrag={x:e.clientX,y:e.clientY,rect:textRect(),corner:e.target.dataset.corner};$('textBox').setPointerCapture(e.pointerId);e.stopPropagation()};$('textBox').onpointermove=e=>{if(!textDrag||!$('textBox').hasPointerCapture(e.pointerId))return;const r=$('art').getBoundingClientRect(),dx=(e.clientX-textDrag.x)/(r.width/item.width),dy=(e.clientY-textDrag.y)/(r.height/item.height),a=textDrag.rect;let l=a.left,t=a.top,rr=a.right,b=a.bottom;if(!textDrag.corner){l+=dx;rr+=dx;t+=dy;b+=dy}else{if(textDrag.corner.includes('w'))l=Math.min(rr-8,Math.max(0,l+dx));if(textDrag.corner.includes('e'))rr=Math.max(l+8,Math.min(item.width,rr+dx));if(textDrag.corner.includes('n'))t=Math.min(b-8,Math.max(0,t+dy));if(textDrag.corner.includes('s'))b=Math.max(t+8,Math.min(item.height,b+dy));}const s=config.scale;config.padding=[t*s,(item.width-rr)*s,(item.height-b)*s,l*s];update()};$('textBox').onpointerup=()=>{textDrag=null};
$('download').onclick=async()=>{if(!item)return toast('先选择 PNG');const response=await fetch(item.url),blob=await response.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=item.filename;a.click();const settings=new Blob([JSON.stringify({version:1,filename:item.filename,config},null,2)],{type:'application/json'});const b=document.createElement('a');b.href=URL.createObjectURL(settings);b.download=item.filename.replace(/\.png$/i,'')+'.bubble.json';b.click();toast('已下载 PNG 和设置文件');};
try{const raw=localStorage.getItem('bubble-studio-handoff');if(raw){const h=JSON.parse(raw);localStorage.removeItem('bubble-studio-handoff');openItem(h.name,h.data,h.config);} }catch(e){toast('读取图片失败');}
