import {CodexPreview} from './codex-preview.mjs';
import {bubbleDefaults,bubbleValid,drawCanvas,styleBubble,paintBubble,bindCanvas} from './editor-core.mjs';

const $=id=>document.getElementById(id);
const copy={
 zh:{library:'在线气泡库',workshop:'气泡工坊',startTitle:'把喜欢的图片，做成聊天气泡。',startDescription:'上传 PNG，调整拉伸线和文字位置，再看看它在聊天里的样子。',create:'我要制作',private:'图片只在当前浏览器中编辑，点击发布后才会提交审核。',editEyebrow:'编辑素材',replace:'更换 PNG',edit:'编辑气泡',reset:'重置',color:'文字颜色',scale:'缩放 %',fit:'适合聊天',radius:'圆角 px',border:'边框 px',borderColor:'边框颜色',save:'保存设置',importSettings:'导入设置',export:'导出设置 ↓',preview:'聊天预览',dark:'深色预览 ☾',light:'浅色预览 ☼',desktop:'在 Codex 模拟页面里预览 ↗',short:'短句',long:'长消息',custom:'自定义',customPlaceholder:'输入你想预览的文字',yourMessage:'你的消息 · 刚刚',assistant:'气泡只用在你发送的消息上。<br>我的回复保持原来的样子。',hint:'试试长消息，检查尾巴、爪子和边角。',composer:'发送消息给 Codex',width:'预览宽度',publish:'我要发布 ↗',reviewNote:'投稿进入私有待审库，审核通过后才会出现在在线气泡库。',desktopTitle:'Codex 模拟预览',publishTitle:'发布气泡',publishIntro:'确认作品信息后提交审核。图片和当前设置会一起送到私有待审库。',nickname:'你的昵称',bubbleName:'气泡名称',consent:'我有权分享此图片，同意审核后展示并提供非商业下载。',submit:'提交审核',saved:'已保存到此浏览器',unsaved:'未保存的调整',shortText:'你好，今天也要开心。',longText:'这是一条长消息，检查猫咪、尾巴、爪子与边角，是否在拉伸时保持原样。',submitted:'已进入待审库，投稿编号：',submitting:'正在提交…',invalid:'请检查拉伸线、缩放和文字位置',choose:'请先选择 PNG',ready:'已导入设置',tooLarge:'PNG 不得超过 2 MB',badPng:'请选择有效的 PNG',badSize:'图片尺寸需在 2–4096 像素内',service:'投稿服务暂不可用，请稍后再试',verification:'请完成人机验证',downloaded:'设置文件已下载',savedTitle:'设置已保存',savedIntro:'想在自己的 Codex 聊天里使用？下载 PNG 和设置文件，在 Codex 新聊天中一起上传，再粘贴下面的说明。',downloadBundle:'下载 PNG + 设置',copyInstructions:'复制给 Codex 的说明',copied:'说明已复制，请在 Codex 中粘贴并附上两个文件'},
 en:{library:'Bubble gallery',workshop:'Bubble workshop',startTitle:'Turn an image you love into a chat bubble.',startDescription:'Upload a PNG, tune the stretch guides and text position, and preview it in a chat.',create:'Create a bubble',private:'Your image stays in this browser until you choose to submit it for review.',editEyebrow:'EDIT',replace:'Choose another PNG',edit:'Edit bubble',reset:'Reset',color:'Text color',scale:'Scale %',fit:'Fit to chat',radius:'Radius px',border:'Border px',borderColor:'Border color',save:'Save settings',importSettings:'Import settings',export:'Export settings ↓',preview:'Chat preview',dark:'Dark preview ☾',light:'Light preview ☼',desktop:'Preview in a Codex window ↗',short:'Short',long:'Long',custom:'Custom',customPlaceholder:'Type a message to preview',yourMessage:'Your message · Just now',assistant:'Bubbles appear only on your messages.<br>My replies keep their original appearance.',hint:'Try a long message to check tails, paws and corners.',composer:'Message Codex',width:'Preview width',publish:'Publish my bubble ↗',reviewNote:'Submissions enter a private review queue and appear in the gallery only after approval.',desktopTitle:'Codex simulation',publishTitle:'Submit your bubble',publishIntro:'Confirm the details below. Your PNG and current settings will be reviewed together.',nickname:'Your nickname',bubbleName:'Bubble name',consent:'I have the right to share this image and allow non-commercial gallery display and downloads after review.',submit:'Submit for review',saved:'Saved in this browser',unsaved:'Unsaved changes',shortText:'Hello! Make today a good day.',longText:'This is a longer message to check whether the cat, tail, paws and corners keep their shape as the bubble stretches.',submitted:'Received for review. Submission ID: ',submitting:'Submitting…',invalid:'Check the stretch guides, scale and text position',choose:'Choose a PNG first',ready:'Settings imported',tooLarge:'PNG must be no larger than 2 MB',badPng:'Choose a valid PNG',badSize:'Image dimensions must be 2–4096 pixels',service:'Submission service is unavailable. Please try later.',verification:'Complete the verification',downloaded:'Settings file downloaded',savedTitle:'Settings saved',savedIntro:'To use this in your Codex chat, download the PNG and settings file, attach both in a new Codex chat, then paste the instructions below.',downloadBundle:'Download PNG + settings',copyInstructions:'Copy instructions for Codex',copied:'Copied. Paste into Codex and attach both files'}
};
let lang=localStorage.getItem('bubble-studio-language')==='en'?'en':'zh',item=null,config=null,sourceImage=null,preview=null,dark=false,mode='short',turnstileId=null,turnstileToken='',endpoint='';
const tr=key=>copy[lang][key];
const defaults=(w,h)=>bubbleDefaults({width:w,height:h});
function toast(message){const el=$('toast');el.textContent=message;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',4000);}
function language(){document.documentElement.lang=lang==='en'?'en':'zh-CN';document.title=lang==='en'?'Bubble workshop · DIY Codex Bubble':'气泡工坊 · DIY Codex Bubble';for(const el of document.querySelectorAll('[data-i18n]')){const value=tr(el.dataset.i18n);if(el.dataset.i18n==='assistant')el.innerHTML=value;else el.textContent=value;}$('customMessage').placeholder=tr('customPlaceholder');$('language').textContent=lang==='en'?'中文':'EN';$('theme').textContent=tr(dark?'light':'dark');$('fullTheme').textContent=tr(dark?'light':'dark');$('textBox').querySelector('span').textContent=lang==='en'?'Aa':'文!';if(item){updateMeta();update();}}
function valid(){return bubbleValid(item,config);}
function readInputs(){config.scale=Number($('scale').value)/100;config.radius=Number($('radius').value);config.borderWidth=Number($('borderWidth').value);config.color=$('color').value;config.borderColor=$('borderColor').value;update(true);}
function fillInputs(){for(const key of ['color','radius','borderWidth','borderColor'])$(key).value=config[key];$('scale').value=Number((config.scale*100).toFixed(2));}
function paint(){if(valid())paintBubble($('previewBubble'),sourceImage,config);}
function update(changed=false){if(!item||!config)return;drawCanvas($('art'),$('textBox'),$('stretchBand'),item,config,{maxHeight:380});const el=$('previewBubble');styleBubble(el,item,config,$('previewWidth').value);el.textContent=mode==='short'?tr('shortText'):mode==='long'?Array.from({length:14},(_,i)=>`${i+1}. ${tr('longText')}`).join('\n'):$('customMessage').value||tr('shortText');$('widthValue').textContent=$('previewWidth').value+' px';requestAnimationFrame(paint);preview?.setAsset(item.url,config).catch(e=>toast(e.message));if(changed)$('saveStatus').textContent=tr('unsaved');$('publish').disabled=!valid();}
function updateMeta(){$('filename').textContent=item.file.name;$('filemeta').textContent=`${item.width} × ${item.height} px · ${(item.file.size/1024).toFixed(1)} KB`;}
async function openFile(file,initial){if(file.size>2*1024*1024)throw Error(tr('tooLarge'));const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length<33||bytes.slice(0,8).join(',')!=='137,80,78,71,13,10,26,10'||String.fromCharCode(...bytes.slice(12,16))!=='IHDR')throw Error(tr('badPng'));const width=new DataView(bytes.buffer).getUint32(16),height=new DataView(bytes.buffer).getUint32(20);if(width<3||height<3||width>4096||height>4096)throw Error(tr('badSize'));const url=URL.createObjectURL(file),image=new Image();image.src=url;try{await image.decode();}catch{URL.revokeObjectURL(url);throw Error(tr('badPng'));}const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),n=>n.toString(16).padStart(2,'0')).join('');if(item)URL.revokeObjectURL(item.url);item={file,url,width,height,hash};sourceImage=image;let saved;try{saved=JSON.parse(localStorage.getItem('bubble-settings-'+hash));}catch{}config={...defaults(width,height),...(initial||saved||{}),width,height};if(!initial&&!saved){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const pixel=ctx.getImageData(Math.floor(width/2),Math.floor(height/2),1,1).data;const luminance=(.2126*pixel[0]+.7152*pixel[1]+.0722*pixel[2])/255;if(pixel[3]>180&&luminance<.48)config.color='#ffffff';}if(!valid())config=defaults(width,height);$('image').src=url;$('start').hidden=true;$('fullPreview').hidden=false;$('workspace').hidden=false;if(!preview)preview=new CodexPreview($('desktopPreview'),{dark});updateMeta();fillInputs();$('saveStatus').textContent=saved&&!initial?tr('saved'):tr('unsaved');requestAnimationFrame(update);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportSettings(){if(!valid())return toast(tr('invalid'));download(new Blob([JSON.stringify({version:1,filename:item.file.name,config},null,2)],{type:'application/json'}),item.file.name.replace(/\.png$/i,'')+'.bubble.json');toast(tr('downloaded'));}
async function openPublish(){if(!valid())return toast(tr('invalid'));const dialog=$('publishDialog');$('publishArt').src=item.url;$('publishFilename').textContent=item.file.name;dialog.showModal();const button=$('sendSubmission'),status=$('submissionStatus');button.disabled=true;status.textContent='';try{const response=await fetch('./submission-config.json');if(!response.ok)throw Error(tr('service'));const settings=await response.json();if(!settings.endpoint||!settings.siteKey)throw Error(tr('service'));endpoint=settings.endpoint;if(!window.turnstile){await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=resolve;script.onerror=reject;document.head.append(script);});}if(turnstileId!==null)window.turnstile.remove(turnstileId);turnstileToken='';turnstileId=window.turnstile.render($('submissionVerification'),{sitekey:settings.siteKey,action:'bubble-submit',callback:token=>{turnstileToken=token;button.disabled=false;},'expired-callback':()=>{turnstileToken='';button.disabled=true;}});}catch(e){status.textContent=e.message;}}
bindCanvas($('art'),$('textBox'),{getItem:()=>item,getConfig:()=>config,onChange:()=>update(true)});
$('create').onclick=$('replace').onclick=()=>$('file').click();$('file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{await openFile(file);}catch(error){toast(error.message);}};
for(const key of ['scale','color','radius','borderWidth','borderColor'])$(key).oninput=readInputs;$('previewWidth').oninput=()=>update();$('customMessage').oninput=()=>update();window.addEventListener('resize',()=>update());new ResizeObserver(paint).observe($('previewBubble'));
$('fit').onclick=()=>{if(!item)return;config.scale=defaults(item.width,item.height).scale;fillInputs();update(true);};$('reset').onclick=()=>{if(!item)return;config=defaults(item.width,item.height);fillInputs();update(true);};$('save').onclick=()=>{if(!valid())return toast(tr('invalid'));try{localStorage.setItem('bubble-settings-'+item.hash,JSON.stringify(config));$('saveStatus').textContent=tr('saved');$('codexInstructions').value=codexPrompt();$('saveDialog').showModal();}catch(e){toast(e.message);}};$('export').onclick=exportSettings;
$('importSettings').onclick=()=>$('settingsFile').click();$('settingsFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||!item)return;try{if(file.size>32768)throw Error(tr('invalid'));const data=JSON.parse(await file.text());if(data.version!==1||!data.config||data.config.width!==item.width||data.config.height!==item.height)throw Error(tr('invalid'));const old=config;config={...defaults(item.width,item.height),...data.config};if(!valid()){config=old;throw Error(tr('invalid'));}fillInputs();update(true);toast(tr('ready'));}catch(error){toast(error.message);}};
for(const button of document.querySelectorAll('[data-mode]'))button.onclick=()=>{mode=button.dataset.mode;for(const option of document.querySelectorAll('[data-mode]'))option.classList.toggle('on',option===button);$('customMessage').hidden=mode!=='custom';update();};
function toggleTheme(){dark=!dark;$('chat').classList.toggle('dark',dark);$('theme').textContent=tr(dark?'light':'dark');$('fullTheme').textContent=tr(dark?'light':'dark');if(preview){preview.dark=dark;preview.build();preview.setAsset(item.url,config).catch(e=>toast(e.message));}}
$('theme').onclick=$('fullTheme').onclick=toggleTheme;$('openDesktop').onclick=()=>$('fullPreview').scrollIntoView({behavior:'smooth',block:'start'});
function codexPrompt(){const repo='https://github.com/kaitongg-bit/DIYcodex-bubble';return lang==='en'?`Please use the attached ${item.file.name} as the bubble for messages I send in Codex. The attached ${item.file.name.replace(/\.png$/i,'')}.bubble.json contains the stretch guides, text placement and appearance settings I saved online. The DIY Codex Bubble project is at ${repo}. If it is not installed on this Mac, follow the repository's macOS setup instructions first. Import the PNG into the local workshop, import its matching settings file, preview short and long messages, then apply this bubble to my own messages.`:`请把附件 ${item.file.name} 应用为我在 Codex 中发送消息的气泡。附件 ${item.file.name.replace(/\.png$/i,'')}.bubble.json 是我在线上工坊调好的拉伸线、文字位置和外观设置。DIY Codex Bubble 项目地址：${repo}。如果这台 Mac 尚未安装，请先按仓库 README 的 macOS 步骤安装并启动工坊；如果已安装，就直接使用现有工坊。导入 PNG 和对应的设置文件，预览短句和长消息后，应用到我发送的消息。`;}
$('closeSave').onclick=()=>$('saveDialog').close();$('downloadBundle').onclick=()=>{if(!item)return;download(item.file,item.file.name);exportSettings();};$('copyInstructions').onclick=async()=>{try{await navigator.clipboard.writeText($('codexInstructions').value);toast(tr('copied'));}catch{$('codexInstructions').select();toast(lang==='en'?'Press ⌘C to copy':'请按 ⌘C 复制');}};
$('publish').onclick=openPublish;$('closePublish').onclick=()=>$('publishDialog').close();$('publishForm').onsubmit=async e=>{e.preventDefault();const button=$('sendSubmission'),status=$('submissionStatus');if(!turnstileToken){status.textContent=tr('verification');return;}button.disabled=true;status.textContent=tr('submitting');try{const form=new FormData(e.target);form.set('png',item.file,item.file.name);form.set('config',JSON.stringify(config));form.set('cf-turnstile-response',turnstileToken);const response=await fetch(endpoint,{method:'POST',body:form}),data=await response.json();if(!response.ok)throw Error(data.error||tr('service'));status.textContent=tr('submitted')+data.id;for(const input of e.target.querySelectorAll('input'))input.disabled=true;button.textContent=lang==='en'?'Submitted':'已提交';}catch(error){status.textContent=error.message;window.turnstile?.reset(turnstileId);turnstileToken='';}};
$('language').onclick=()=>{lang=lang==='zh'?'en':'zh';localStorage.setItem('bubble-studio-language',lang);language();};language();
try{const raw=localStorage.getItem('bubble-studio-handoff');if(raw){localStorage.removeItem('bubble-studio-handoff');const handoff=JSON.parse(raw),bytes=Uint8Array.from(atob(handoff.data),c=>c.charCodeAt(0)),file=new File([bytes],handoff.name,{type:'image/png'});openFile(file,handoff.config).catch(e=>toast(e.message));}}catch(e){toast(e.message);}
