import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {platforms,profileFor,acceptsTarget} from '../app/platforms.mjs';import {renderNineSlice} from '../app/static/nine-slice.mjs';
const source=fs.readFileSync(new URL('../app/bridge.mjs',import.meta.url),'utf8').replace(/^import .*;$/gm,'');
const page=(url,socket='ws://ok')=>({type:'page',url,webSocketDebuggerUrl:socket});
async function run({key='doubao',pages=[page('https://www.doubao.com/chat/')],state={},action='status'}={}){
 let output,expression,endpoint;const sockets=[];
 class Socket{constructor(url){sockets.push(url);queueMicrotask(()=>url==='ws://fail'?this.onerror?.():this.onopen?.());}send(data){expression=JSON.parse(data).params.expression;queueMicrotask(()=>this.onmessage?.({data:JSON.stringify({id:1,result:{result:{value:{matched:2}}}})}));}close(){}}
 await vm.runInNewContext('(async()=>{'+source+'})()',{fs:{readFileSync:p=>p==='state'?JSON.stringify(state):fs.readFileSync(p)},process:{argv:['node','bridge','state',action,key]},platforms,profileFor,acceptsTarget,renderNineSlice,WebSocket:Socket,fetch:async url=>(endpoint=url,{ok:true,json:async()=>pages}),AbortSignal:{timeout:()=>null},setTimeout,clearTimeout,queueMicrotask,console:{log:v=>output=JSON.parse(v)}});
 return{output,expression,endpoint,sockets};
}
test('Fresh Doubao has built-in selector; legacy active belongs only to Codex',()=>{const old={active:{id:'legacy'}};assert.equal(profileFor(old,'doubao').active,null);assert.equal(profileFor(old,'codex').active.id,'legacy');assert.equal(profileFor({},'doubao').userSelector,'[class~="bg-g-send-msg-bubble-bg"]');assert.equal(profileFor({userSelector:'*'},'doubao').userSelector,platforms.doubao.userSelector);});
test('Override is scoped to its platform',()=>{const state={platforms:{doubao:{userSelector:'.custom',active:null}}};assert.equal(profileFor(state,'doubao').userSelector,'.custom');assert.equal(profileFor(state,'codex').userSelector,'');});
test('Target allowlist excludes unrelated pages and lookalike domains',()=>{for(const url of ['https://evil-doubao.com/chat','https://doubao.com.evil.test','https://example.com/','about:blank','doubao://doubao-background','doubao://evil','doubao://doubao-chat.evil'])assert.equal(acceptsTarget(page(url),'doubao'),false);assert.equal(acceptsTarget(page('https://www.doubao.com/chat/'),'doubao'),true);assert.equal(acceptsTarget(page('doubao://doubao-chat'),'doubao'),true);assert.equal(acceptsTarget(page('app://-/'),'codex'),true);assert.equal(acceptsTarget(page('https://www.doubao.com/chat/'),'codex'),false);});
test('All failed pages do not report connected',async()=>{const {output}=await run({pages:[page('https://www.doubao.com/chat/','ws://fail')]});assert.equal(output.connected,false);assert.equal(output.skipped,1);});
test('One failed page does not block another; no unrelated target gets evaluated',async()=>{const {output,sockets}=await run({pages:[page('https://www.doubao.com/chat/','ws://fail'),page('https://www.doubao.com/chat/'),page('https://example.com/','ws://other')]});assert.equal(output.connected,true);assert.equal(output.matched,2);assert.equal(output.succeeded,1);assert.equal(output.skipped,1);assert.deepEqual(sockets,['ws://fail','ws://ok']);});
test('Generated apply expression uses exact Doubao selector and retains expand fix',async()=>{const preset=JSON.parse(fs.readFileSync(new URL('../presets/manifest.json',import.meta.url))).items[0];const active={version:'test',path:new URL('../presets/alien-cat.png',import.meta.url).pathname,config:preset.config};const result=await run({action:'apply',state:{platforms:{doubao:{active}}}});new Function('return '+result.expression);assert.equal(result.endpoint,'http://127.0.0.1:19326/json/list');assert.ok(result.expression.includes('bg-g-send-msg-bubble-bg'));assert.ok(result.expression.includes('button[aria-expanded]'));assert.ok(!result.expression.includes("querySelectorAll('div,section,span')"));assert.ok(!result.expression.includes('__codexCatBubble?.remove()'));});
test('Observed Doubao native chat protocol is accepted; background and iframe are excluded',async()=>{const {output,sockets}=await run({pages:[{...page('doubao://doubao-chat','ws://other'),type:'other'},page('doubao://doubao-chat','ws://native'),page('doubao://doubao-background','ws://background'),{...page('https://www.doubao.com/','ws://iframe'),type:'iframe'}]});assert.equal(output.connected,true);assert.equal(output.pages,1);assert.deepEqual(sockets,['ws://native']);});
