import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import worker,{validateSubmission,storeSubmission} from '../community/worker.mjs';
const png=readFileSync(new URL('../presets/love.png',import.meta.url));
function request(changes={}){const f=new FormData();for(const [k,v] of Object.entries({nickname:'demo',name:'bubble',consent:'yes',...changes}))f.set(k,v);f.set('png',new Blob([png],{type:'image/png'}),'bubble.png');return new Request('https://worker.example/api/submissions',{method:'POST',body:f});}
test('valid PNG preserves exact bytes and marks pending',async()=>{const result=await validateSubmission(request());assert.deepEqual(Buffer.from(result.bytes),png);assert.equal(result.metadata.status,'pending');assert.equal(result.metadata.width,198);assert.equal(result.metadata.sha256.length,64);});
test('submission keeps tuned settings and rejects mismatched dimensions',async()=>{const config={width:198,height:162,left:64,right:128,top:70,bottom:92,scale:.6,padding:[16,18,17,19],color:'#ffffff',radius:0,borderWidth:0,borderColor:'#d0d0d0'};const accepted=await validateSubmission(request({config:JSON.stringify(config)}));assert.deepEqual(accepted.metadata.config,config);await assert.rejects(validateSubmission(request({config:JSON.stringify({...config,width:420})})),/Invalid bubble settings/);});
test('consent and bounded display names required',async()=>{await assert.rejects(validateSubmission(request({consent:'no'})));await assert.rejects(validateSubmission(request({nickname:'x'.repeat(41)})));await assert.rejects(validateSubmission(request({website:'spam'})));});
test('private queue refusal happens before upload',async()=>{let calls=0;await assert.rejects(storeSubmission(await validateSubmission(request()),{QUEUE_REPO:'owner/queue',GITHUB_TOKEN:'test'},async()=>{calls++;return new Response(JSON.stringify({private:false}),{status:200});}),/private/);assert.equal(calls,1);});
test('missing secrets do not accept anonymous submissions',async()=>{const r=await worker.fetch(new Request('https://worker.example/api/submissions',{method:'POST',headers:{Origin:'https://kaitongg-bit.github.io'}}),{});assert.equal(r.status,503);});
test('unknown origins cannot submit or see CORS permission',async()=>{const r=await worker.fetch(new Request('https://worker.example/api/submissions',{method:'POST',headers:{Origin:'https://evil.example'}}),{});assert.equal(r.status,403);assert.equal(r.headers.get('Access-Control-Allow-Origin'),null);});
