import fs from 'node:fs';
const state=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const action=process.argv[3]||'status';
const endpoint=`http://127.0.0.1:${state.debugPort||19327}`;
function css(c,image){const w=c.width,h=c.height,s=c.scale;const slices=[c.top,w-c.right,h-c.bottom,c.left];const widths=slices.map(v=>v*s+'px').join(' ');return `.bubble-studio-user{position:relative!important;isolation:isolate;box-sizing:border-box!important;min-width:${w*s}px!important;min-height:${h*s}px!important;padding:${c.padding.map(v=>v+'px').join(' ')}!important;background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;color:${c.color}!important;--color-text-user-message:${c.color};--compact-user-message-bubble-foreground:${c.color}}.bubble-studio-user::before{content:"";position:absolute;inset:0;z-index:-1;pointer-events:none;border:solid transparent;border-width:${widths};border-image:url("${image}") ${slices.join(' ')} fill / ${widths} / 0 stretch;}.bubble-studio-user [class*="_markdownContent_"]{color:inherit!important}`;}
function buildExpression(){if(action==='status')return `({matched:document.querySelectorAll('.bubble-studio-user').length,legacyMatched:document.querySelectorAll('.codex-cat-user-bubble').length,active:!!window.__bubbleStudio})`;
if(action==='restore')return `(()=>{window.__bubbleStudio?.remove();window.__codexCatBubble?.remove();return {matched:0,restored:true}})()`;
if(!state.active)return '({matched:0})';
const c=state.active.config;const image='data:image/png;base64,'+fs.readFileSync(state.active.path).toString('base64');const styles=css(c,image);const version=state.active.version;
return `(()=>{if(window.__bubbleStudio?.version===${JSON.stringify(version)})return window.__bubbleStudio.status();window.__codexCatBubble?.remove();window.__bubbleStudio?.remove();const style=document.createElement('style');style.id='bubble-studio-style';style.textContent=${JSON.stringify(styles)};document.head.append(style);const sync=()=>{document.querySelectorAll('[class~="bg-user-message"][class~="text-user-message"][class~="max-w-(--user-chat-width)"]').forEach(el=>{if(!el.closest('aside,[role="dialog"]')&&!el.classList.contains('bubble-studio-user'))el.classList.add('bubble-studio-user')});document.querySelectorAll('[class*="_markdownContent_"]').forEach(el=>{const bubble=el.closest('[class~="bg-token-foreground/5"][class~="rounded-2xl"]');if(bubble&&!bubble.closest('aside,[role="dialog"]')&&!bubble.classList.contains('bubble-studio-user'))bubble.classList.add('bubble-studio-user')});};const observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true});sync();window.__bubbleStudio={version:${JSON.stringify(version)},status:()=>({matched:document.querySelectorAll('.bubble-studio-user').length}),remove(){observer.disconnect();style.remove();document.querySelectorAll('.bubble-studio-user').forEach(el=>el.classList.remove('bubble-studio-user'));delete window.__bubbleStudio;}};return window.__bubbleStudio.status();})()`;
}
const expression=buildExpression();
async function evaluate(t){const ws=new WebSocket(t.webSocketDebuggerUrl);try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('connection timed out')),3000);ws.onopen=()=>{clearTimeout(timer);resolve()};ws.onerror=()=>{clearTimeout(timer);reject(Error('connection failed'))}});return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('evaluation timed out')),4000);ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.id!==1)return;clearTimeout(timer);if(m.error||m.result?.exceptionDetails)reject(Error('evaluation failed'));else resolve(m.result.result.value)};ws.send(JSON.stringify({id:1,method:'Runtime.evaluate',params:{expression,returnByValue:true}}))});}finally{ws.close()}}
try{const response=await fetch(endpoint+'/json/list',{signal:AbortSignal.timeout(2000)});const targets=(await response.json()).filter(t=>t.type==='page'&&/^app:\/\/-\//.test(t.url)&&t.webSocketDebuggerUrl);if(!targets.length)throw Error('no app page');let matched=0,legacyMatched=0;for(const t of targets){const r=await evaluate(t);matched+=r?.matched||0;legacyMatched+=r?.legacyMatched||0}console.log(JSON.stringify({connected:true,matched,legacyMatched,pages:targets.length}));}catch{console.log(JSON.stringify({connected:false,matched:0,message:'调试连接未开启，请使用「启动 Codex 并换肤」。'}));}
